services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: awesome-pizza-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "AwesomePizza!Dev123"
    ports:
      - "14330:1433"
    volumes:
      - sqldata:/var/opt/mssql

volumes:
  sqldata:
